/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_hm_1;

import com.google.gson.GsonBuilder;

public class App {
    public static void main(String[] args) {
        Person person = new Person("Igor", "Petrenko");
        System.out.println(new GsonBuilder().create().toJson(person));
    }
}
